spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:
    driver: h2
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true

security:
  jwt:
    secret-key: bWkgY2xhdmUgZXMgbXV5IHNlZ3VyYSAxMjM0NTY3OCBhYmNkZWZn
    expiration-in-minutes: '20'
